---
title: "Introduction to R | PSY4373"
author:
  - "Ehsan Pishva"
  - "Wolfgang Viechtbauer"
output: html_document
date: "`r format(Sys.time(), '%d %B, %Y')`"
---

### Description

R is a programming language and software environment for carrying out computations, manipulating and analyzing data, and creating various types of plots and graphics. R has become the 'lingua franca of statistics' and the software of choice for analyzing data in various disciplines. The purpose of this course is to lay the necessary foundation for becoming a proficient R user.

### Contents

In this course, we will cover:

- a bit of history and the development of R
- how to use and interact with R
- basic data structures
- data import and export
- data inspection and manipulation
- methods for graphing data
- t-tests and analysis of (co)variance
- correlations and linear regression
- categorical data analysis and logistic regression
- add-on packages (how to find, install, and work with them)
- how/where to obtain help when you get stuck
- basic programming structures (e.g., loops, if-else statements)
- writing documents with Rmarkdown

### Preparations

1. You will need to **install the current version of R** on your computer (the current version is 4.3.0). You can download R from the [Comprehensive R Archive Network](https://cran.r-project.org) (CRAN). If you use Windows, choose "Download R for Windows", then "base", and then download and run the setup program. You can go with the default settings during the installation process. R is also available for macOS and Linux for those using these operating systems (installation instructions can be found on CRAN).

   If you already have R installed on your computer, please check its version number and release date (just start R and it will tell you at the very top). If you do not have the current version installed, please update to the current version (just follow the instructions above).

2. Please also **install RStudio**, an integrated development environment (IDE) for R. It provides some useful features that make it a bit easier to work with R (to be discussed in more detail during the course). You can download RStudio for free from [here](https://posit.co/download/rstudio-desktop/). Download the appropriate file (Windows / macOS / etc) and install it in the usual manner (note that you must have R installed first for RStudio to work).

### Materials

The materials for this course can be downloaded as a zip file [here](https://github.com/ehsanpishva/IntroR-PSY4373/blob/main/scripts/intro_to_r_materials.zip). Make sure to properly extract the files from the zip file and place them in a directory/folder somewhere on your computer.

### Links

- [UM Page for PSY4373](https://curriculum.maastrichtuniversity.nl/meta/437595/introduction-r)
- [Canvas Page for PSY4373](https://maastrichtuniversity.instructure.com/courses/10474)
- [R Project Website](https://www.r-project.org)
- [Comprehensive R Archive Network](https://cran.r-project.org)
- [RStudio Download](https://posit.co/download/rstudio-desktop/)
