---
title: "Introduction to R | PSY4373"
subtitle: "Week 1 - Extra"
output: html_document
---

---

### Self-Study

For this week's self-study part, you will need these files:

- [data_survey.dat](FIX ME!) (the dataset)
- [data_survey.pdf](FIX ME!) (the corresponding code book)
- [intro_to_r_week_1_extra.r](FIX ME!) (the R script)

This self-study part covers the following topics:

- data import
- inspection of data frames
- summary statistics of quantitative variables
- frequency tables
- reading the help file of a function
- summary statistics for subsets
- reverse coding items
- data export

---

### Exercise 1

For the exercise, you will need this dataset:

- [inflammation.csv](FIX ME!)

Create a new script file for this exercise and save it to the same directory/folder where you have saved the dataset to. Next, set the working directory to this directory/folder. Then you can import the dataset with:

```{r, eval = FALSE}
dat <- read.csv("inflammation.csv")
```

The dataset contains a [cytokine](https://en.wikipedia.org/wiki/Cytokine) measurement for 40 consecutive days in 60 individuals.

1. Select from the data frame `dat`:

    - The element on the 4th row and 2nd column.

    - The element on the 7th row and 5th column.

    - The 10th row.

    - The 3rd column.

2. Calculate some summary statistics for specific individuals (rows) and days (columns).

    - Calculate the mean inflammation score for the first individual.

    - Calculate the median inflammation score for the 5th day.

    - Use `min()` and `max()` to calculate the range of values for the 10th individual.

    - Check you answer with the `range()` function.

    - Use `quantile()` to calculate the [interquartile range](https://en.wikipedia.org/wiki/Interquartile_range) of the 6th individual.

3. Let's pretend there was something wrong with the instrument on the first five days for every second patient (2, 4, 6, etc.), which resulted in the measurements being twice as large as they should be.

    - Write a vector containing each affected patient (hint: `help(seq)`).

    - Create a new data frame in which you halve the first five days' values in only those patients.

    - Print out the corrected data frame to check that your code has fixed the problem.

---

### Solution

Go to the link below if you want to compare your script to the solution.

[Solution script GitHub](https://github.com/ehsanpishva/IntroR-PSY4373/blob/main/Scripts/IntroR_solution_exercise_1.R)

[Solution script RAW](https://raw.githubusercontent.com/ehsanpishva/IntroR-PSY4373/main/Scripts/IntroR_solution_exercise_1.R)

---
