---
title: "Introduction to R | PSY4373"
subtitle: "Week 2 - Extra"
output: html_document
---

---

### Self-Study

For this week's self-study part, you will need these files:

- [data_survey_edit.rdata](https://www.dropbox.com/s/ti8z282h15dyutx/data_survey_edit.rdata?dl=1) (the dataset after the data preparation)
- [data_survey.pdf](https://www.dropbox.com/s/kbfisevspr0sk4m/data_survey.pdf?dl=1) (the corresponding code book)
- [intro_to_r_week_2_extra.r](https://www.dropbox.com/s/wfx0lgmhz0ofsya/intro_to_r_week_2_extra.r?dl=1) (the R script)

This self-study part covers the following topics:

- stratified summary statistics
- plot of group means
- boxplots for multiple groups
- stripcharts / dot plot
- violin/bean/beeswarm plots
- adjusting the axis values

---

### Exercise 2

In this exercise, we will continue to work with the dataset in `data_survey_edit.rdata`.

Part A:

  - Create a boxplot showing negative affect by marital status.

  - But this doesn't look that great, so let's do some modifications:

      1) Do not show the supposed outliers (hint: check the `range` argument under `help(boxplot)`).
      2) Adjust the range of the y-axis so that it goes from 10 to 50 (the minimum and maximum possible values for the `negaff` scale).
      3) Make the boxplot horizontal and adjust the orientation of the axis labels. Note that you need to make the margin on the left larger so that the marital state labels fit.
      4) Create a nicer x-axis label and suppress the y-axis label.
      5) Use a different color for each marital state.
      6) Superimpose the actual data with some jitter on top of the boxplot with the `stripchart()` function.

Part B:

  - Create a scatterplot showing the association between the Rosenberg Self-Esteem Scale on the x-axis and negative affect on the y-axis.

  - Use a filled circle as the plotting symbol and jitter the points slightly.

  - Adjust the range of the x-axis and y-axis, so that they correspond to their possible range of values (check `data_survey.pdf`).

  - Create nicer labels for x-axis and y-axis.

  - Color label the points based on sex.

  - Also use different symbols for male and female participants.

  - Add a legend at the bottom left.

---
